### ISSUE TITLE
The system freezes after about 10 minutes of operation

### ISSUE THREAD

**Issue by baby0o01999** [1401199262/HookKdTrap#1]
Microsoft Windows [Version 10.0.18362.145]

The system freezes after about 10 minutes of operation

**Comment by 1401199262** [comment]
This is a issue on real machine, i will fix this when i have a better debugging tool.
<img src="https://user-images.githubusercontent.com/55327538/222542673-16a9d462-80ff-45a9-9b32-5fdd8f2c5de2.gif"  width="200" height="200">

**Comment by 1401199262** [comment]
[#4b2346e](https://github.com/1401199262/Hook-KdTrap/commit/4b2346e40417bff2768c6a1567f5635883307ccd)
